import { Pool, neonConfig } from '@neondatabase/serverless';
import { drizzle } from 'drizzle-orm/neon-serverless';
import ws from "ws";
import * as schema from "@shared/schema";

neonConfig.webSocketConstructor = ws;

if (!process.env.DATABASE_URL) {
  throw new Error(
    "DATABASE_URL must be set. Did you forget to provision a database?",
  );
}

export const pool = new Pool({ connectionString: process.env.DATABASE_URL });
export const db = drizzle({ client: pool, schema });

const compatibilityStatements = [
  `CREATE TABLE IF NOT EXISTS users (
    id serial PRIMARY KEY,
    full_name text NOT NULL,
    email text NOT NULL UNIQUE,
    password_hash text,
    role text NOT NULL DEFAULT 'pm',
    signature_name text,
    job_title text,
    mobile_phone text,
    is_active boolean NOT NULL DEFAULT true,
    must_change_password boolean NOT NULL DEFAULT false,
    created_at timestamp DEFAULT now() NOT NULL
  )`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS signature_name text`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS job_title text`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS mobile_phone text`,
  `CREATE TABLE IF NOT EXISTS user_email_connections (
    id serial PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    provider text NOT NULL DEFAULT 'zoho_mail',
    provider_email text,
    provider_account_id text,
    provider_user_id text,
    provider_org_id text,
    encrypted_refresh_token text,
    encrypted_access_token text,
    access_token_expires_at timestamp,
    scopes text,
    status text NOT NULL DEFAULT 'disconnected',
    last_connected_at timestamp,
    last_validated_at timestamp,
    revoked_at timestamp,
    created_at timestamp DEFAULT now() NOT NULL,
    updated_at timestamp DEFAULT now() NOT NULL
  )`,
  `ALTER TABLE user_email_connections ADD COLUMN IF NOT EXISTS user_id integer REFERENCES users(id) ON DELETE CASCADE`,
  `ALTER TABLE user_email_connections ADD COLUMN IF NOT EXISTS provider text DEFAULT 'zoho_mail'`,
  `ALTER TABLE user_email_connections ADD COLUMN IF NOT EXISTS provider_email text`,
  `ALTER TABLE user_email_connections ADD COLUMN IF NOT EXISTS provider_account_id text`,
  `ALTER TABLE user_email_connections ADD COLUMN IF NOT EXISTS provider_user_id text`,
  `ALTER TABLE user_email_connections ADD COLUMN IF NOT EXISTS provider_org_id text`,
  `ALTER TABLE user_email_connections ADD COLUMN IF NOT EXISTS encrypted_refresh_token text`,
  `ALTER TABLE user_email_connections ADD COLUMN IF NOT EXISTS encrypted_access_token text`,
  `ALTER TABLE user_email_connections ADD COLUMN IF NOT EXISTS access_token_expires_at timestamp`,
  `ALTER TABLE user_email_connections ADD COLUMN IF NOT EXISTS scopes text`,
  `ALTER TABLE user_email_connections ADD COLUMN IF NOT EXISTS status text DEFAULT 'disconnected'`,
  `ALTER TABLE user_email_connections ADD COLUMN IF NOT EXISTS last_connected_at timestamp`,
  `ALTER TABLE user_email_connections ADD COLUMN IF NOT EXISTS last_validated_at timestamp`,
  `ALTER TABLE user_email_connections ADD COLUMN IF NOT EXISTS revoked_at timestamp`,
  `ALTER TABLE user_email_connections ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now()`,
  `ALTER TABLE user_email_connections ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now()`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_user_email_connections_user_provider ON user_email_connections(user_id, provider)`,
  `CREATE TABLE IF NOT EXISTS email_oauth_states (
    id serial PRIMARY KEY,
    state text NOT NULL UNIQUE,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    provider text NOT NULL DEFAULT 'zoho_mail',
    expires_at timestamp NOT NULL,
    used_at timestamp,
    created_at timestamp DEFAULT now() NOT NULL
  )`,
  `ALTER TABLE email_oauth_states ADD COLUMN IF NOT EXISTS state text`,
  `ALTER TABLE email_oauth_states ADD COLUMN IF NOT EXISTS user_id integer REFERENCES users(id) ON DELETE CASCADE`,
  `ALTER TABLE email_oauth_states ADD COLUMN IF NOT EXISTS provider text DEFAULT 'zoho_mail'`,
  `ALTER TABLE email_oauth_states ADD COLUMN IF NOT EXISTS expires_at timestamp`,
  `ALTER TABLE email_oauth_states ADD COLUMN IF NOT EXISTS used_at timestamp`,
  `ALTER TABLE email_oauth_states ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now()`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_email_oauth_states_state ON email_oauth_states(state)`,
  `CREATE INDEX IF NOT EXISTS idx_email_oauth_states_user_provider ON email_oauth_states(user_id, provider)`,
  `CREATE TABLE IF NOT EXISTS email_templates (
    id serial PRIMARY KEY,
    template_type text NOT NULL,
    language text NOT NULL,
    subject text NOT NULL,
    body text NOT NULL,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    updated_by integer REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamp DEFAULT now() NOT NULL,
    updated_at timestamp DEFAULT now() NOT NULL
  )`,
  `ALTER TABLE email_templates ADD COLUMN IF NOT EXISTS template_type text`,
  `ALTER TABLE email_templates ADD COLUMN IF NOT EXISTS language text`,
  `ALTER TABLE email_templates ADD COLUMN IF NOT EXISTS subject text`,
  `ALTER TABLE email_templates ADD COLUMN IF NOT EXISTS body text`,
  `ALTER TABLE email_templates ADD COLUMN IF NOT EXISTS description text`,
  `ALTER TABLE email_templates ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true`,
  `ALTER TABLE email_templates ADD COLUMN IF NOT EXISTS updated_by integer REFERENCES users(id) ON DELETE SET NULL`,
  `ALTER TABLE email_templates ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now()`,
  `ALTER TABLE email_templates ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now()`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_email_templates_type_language ON email_templates(template_type, language)`,
  `CREATE TABLE IF NOT EXISTS clients (
    id serial PRIMARY KEY,
    client_name text NOT NULL,
    country text,
    region text,
    industry text,
    main_contact_name text,
    main_contact_email text,
    main_contact_phone text,
    notes text,
    status text NOT NULL DEFAULT 'prospect',
    created_at timestamp DEFAULT now() NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS client_organizations (
    id serial PRIMARY KEY,
    name text NOT NULL,
    industry text NOT NULL,
    client_type text,
    legal_entity_name text,
    contract_type text,
    pricing_model text,
    currency text DEFAULT 'USD',
    default_cu_rate numeric(10,2),
    purchased_cu numeric(10,2),
    retainer_cu_allowance numeric(10,2),
    retainer_period text,
    contracted_cu numeric(10,2),
    payment_terms text,
    contract_start_date timestamp,
    contract_end_date timestamp,
    credit_balance numeric(10,2),
    retainer_balance numeric(10,2),
    commercial_notes text,
    billing_address text,
    main_pm_id integer REFERENCES users(id),
    total_cu_used numeric(10,2) DEFAULT 0,
    created_at timestamp DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS client_pocs (
    id serial PRIMARY KEY,
    organization_id integer NOT NULL REFERENCES client_organizations(id) ON DELETE CASCADE,
    name text NOT NULL,
    email text NOT NULL,
    phone text,
    job_title text,
    created_at timestamp DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS companies (
    id serial PRIMARY KEY,
    name text NOT NULL,
    normalized_name text NOT NULL,
    legal_name text,
    official_website text,
    linkedin_url text,
    country text NOT NULL,
    company_type text NOT NULL,
    industry text,
    city text,
    description text,
    ownership_notes text,
    notes text,
    status text NOT NULL DEFAULT 'active',
    dnc_status text NOT NULL DEFAULT 'none',
    verification_status text NOT NULL DEFAULT 'unverified',
    created_at timestamp DEFAULT now() NOT NULL,
    updated_at timestamp DEFAULT now() NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS company_aliases (
    id serial PRIMARY KEY,
    company_id integer NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    alias text NOT NULL,
    normalized_alias text NOT NULL,
    created_at timestamp DEFAULT now() NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS projects (
    id serial PRIMARY KEY,
    name text NOT NULL,
    project_overview text,
    client_organization_id integer REFERENCES client_organizations(id),
    client_name text NOT NULL,
    client_company text,
    client_poc_name text,
    client_poc_email text,
    client_request_notes text,
    description text,
    industry text NOT NULL,
    region text,
    status text NOT NULL DEFAULT 'new',
    budget numeric(10,2),
    start_date timestamp,
    end_date timestamp,
    due_date timestamp,
    created_by_pm_id integer REFERENCES users(id),
    assigned_ra_id integer REFERENCES users(id),
    assigned_ra_ids integer[],
    total_cu_used numeric(10,2) DEFAULT 0,
    cu_rate_per_cu numeric(10,2) DEFAULT 1150,
    created_at timestamp DEFAULT now() NOT NULL,
    updated_at timestamp DEFAULT now() NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS experts (
    id serial PRIMARY KEY,
    name text NOT NULL,
    email text NOT NULL UNIQUE,
    password_hash text,
    phone text,
    linkedin_url text,
    country text,
    city text,
    timezone text,
    whatsapp text,
    expertise text NOT NULL,
    sector_expertise text,
    regional_expertise text,
    areas_of_expertise text[],
    industry text NOT NULL,
    company text,
    past_employers text[],
    job_title text,
    years_of_experience integer NOT NULL,
    hourly_rate numeric(10,2) NOT NULL,
    bio text,
    work_history jsonb,
    biography text,
    status text NOT NULL DEFAULT 'available',
    available_now boolean DEFAULT true,
    next_available_date timestamp,
    total_hours_worked numeric(10,2) DEFAULT 0,
    recruited_by text,
    sourced_by_ra_id integer REFERENCES users(id),
    sourced_at timestamp,
    terms_accepted boolean DEFAULT false,
    lgpd_accepted boolean DEFAULT false,
    billing_info text,
    languages text[],
    created_at timestamp DEFAULT now() NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS project_angles (
    id serial PRIMARY KEY,
    project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    title text NOT NULL,
    description text,
    order_index integer DEFAULT 0,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS vetting_questions (
    id serial PRIMARY KEY,
    project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    angle_id integer REFERENCES project_angles(id) ON DELETE CASCADE,
    question text NOT NULL,
    question_type text DEFAULT 'text',
    order_index integer DEFAULT 0,
    is_required boolean DEFAULT true,
    created_at timestamp DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS project_experts (
    id serial PRIMARY KEY,
    project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    expert_id integer NOT NULL REFERENCES experts(id) ON DELETE CASCADE,
    status text DEFAULT 'assigned',
    invitation_status text DEFAULT 'not_invited',
    pipeline_status text DEFAULT 'interested',
    source_type text DEFAULT 'internal_db',
    consent_language text,
    terms_version text,
    privacy_policy_version text,
    assigned_at timestamp DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS call_records (
    id serial PRIMARY KEY,
    project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    expert_id integer NOT NULL REFERENCES experts(id) ON DELETE CASCADE,
    call_date timestamp NOT NULL,
    timezone text,
    duration_minutes integer NOT NULL,
    cu_used numeric(10,2) NOT NULL,
    status text DEFAULT 'pending',
    created_at timestamp DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS insights (
    id serial PRIMARY KEY,
    consultation_id text NOT NULL,
    call_record_id integer REFERENCES call_records(id) ON DELETE SET NULL,
    month text NOT NULL,
    call_date timestamp NOT NULL,
    client_type text NOT NULL,
    industry text NOT NULL,
    market text NOT NULL,
    geography text NOT NULL,
    client_question text NOT NULL,
    observed_trend text NOT NULL,
    key_tags text[],
    signal_strength text NOT NULL,
    company_mentioned text,
    expert_seniority text,
    call_duration_min integer,
    recording_link text,
    transcript_link text,
    internal_notes text,
    created_at timestamp DEFAULT now() NOT NULL,
    updated_at timestamp DEFAULT now() NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS expert_invitation_links (
    id serial PRIMARY KEY,
    token text NOT NULL UNIQUE,
    project_id integer REFERENCES projects(id) ON DELETE CASCADE,
    ra_id integer REFERENCES users(id),
    expert_id integer REFERENCES experts(id),
    invite_type text DEFAULT 'general',
    status text DEFAULT 'pending',
    recruited_by text DEFAULT 'system',
    is_active boolean DEFAULT true,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS project_activities (
    id serial PRIMARY KEY,
    project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    user_id integer REFERENCES users(id),
    expert_id integer REFERENCES experts(id),
    activity_type text NOT NULL,
    description text NOT NULL,
    metadata jsonb,
    created_at timestamp DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS usage_records (
    id serial PRIMARY KEY,
    project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    expert_id integer NOT NULL REFERENCES experts(id) ON DELETE CASCADE,
    call_date timestamp NOT NULL,
    duration_minutes integer NOT NULL,
    credits_used numeric(10,2) NOT NULL,
    notes text,
    created_at timestamp DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS billable_usage (
    id serial PRIMARY KEY,
    call_record_id integer NOT NULL UNIQUE REFERENCES call_records(id) ON DELETE RESTRICT,
    client_organization_id integer REFERENCES client_organizations(id),
    project_id integer NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
    expert_id integer NOT NULL REFERENCES experts(id) ON DELETE RESTRICT,
    call_date timestamp NOT NULL,
    cu_used numeric(10,2) NOT NULL,
    currency text NOT NULL DEFAULT 'USD',
    cu_rate numeric(10,2),
    amount numeric(10,2),
    status text NOT NULL DEFAULT 'unbilled',
    source text NOT NULL DEFAULT 'completed_call_record',
    adjustment_reason text,
    created_at timestamp DEFAULT now() NOT NULL,
    updated_at timestamp DEFAULT now() NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS expert_payables (
    id serial PRIMARY KEY,
    consultation_id integer NOT NULL UNIQUE REFERENCES call_records(id) ON DELETE RESTRICT,
    project_id integer NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
    expert_id integer NOT NULL REFERENCES experts(id) ON DELETE RESTRICT,
    client_organization_id integer REFERENCES client_organizations(id) ON DELETE SET NULL,
    service_date timestamp NOT NULL,
    duration_minutes integer NOT NULL,
    expert_hourly_rate_snapshot numeric(10,2) NOT NULL,
    payout_currency text NOT NULL DEFAULT 'USD',
    payable_amount numeric(12,2) NOT NULL,
    status text NOT NULL DEFAULT 'pending_review',
    approved_at timestamp,
    approved_by_user_id integer REFERENCES users(id) ON DELETE SET NULL,
    paid_at timestamp,
    paid_by_user_id integer REFERENCES users(id) ON DELETE SET NULL,
    payment_method text,
    payment_reference_number text,
    payment_notes text,
    voided_at timestamp,
    voided_by_user_id integer REFERENCES users(id) ON DELETE SET NULL,
    void_reason text,
    created_at timestamp DEFAULT now() NOT NULL,
    updated_at timestamp DEFAULT now() NOT NULL
  )`,
  `ALTER TABLE expert_payables ADD COLUMN IF NOT EXISTS consultation_id integer REFERENCES call_records(id) ON DELETE RESTRICT`,
  `ALTER TABLE expert_payables ADD COLUMN IF NOT EXISTS project_id integer REFERENCES projects(id) ON DELETE RESTRICT`,
  `ALTER TABLE expert_payables ADD COLUMN IF NOT EXISTS expert_id integer REFERENCES experts(id) ON DELETE RESTRICT`,
  `ALTER TABLE expert_payables ADD COLUMN IF NOT EXISTS client_organization_id integer REFERENCES client_organizations(id) ON DELETE SET NULL`,
  `ALTER TABLE expert_payables ADD COLUMN IF NOT EXISTS service_date timestamp`,
  `ALTER TABLE expert_payables ADD COLUMN IF NOT EXISTS duration_minutes integer`,
  `ALTER TABLE expert_payables ADD COLUMN IF NOT EXISTS expert_hourly_rate_snapshot numeric(10,2)`,
  `ALTER TABLE expert_payables ADD COLUMN IF NOT EXISTS payout_currency text DEFAULT 'USD'`,
  `ALTER TABLE expert_payables ADD COLUMN IF NOT EXISTS payable_amount numeric(12,2)`,
  `ALTER TABLE expert_payables ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending_review'`,
  `ALTER TABLE expert_payables ADD COLUMN IF NOT EXISTS approved_at timestamp`,
  `ALTER TABLE expert_payables ADD COLUMN IF NOT EXISTS approved_by_user_id integer REFERENCES users(id) ON DELETE SET NULL`,
  `ALTER TABLE expert_payables ADD COLUMN IF NOT EXISTS paid_at timestamp`,
  `ALTER TABLE expert_payables ADD COLUMN IF NOT EXISTS paid_by_user_id integer REFERENCES users(id) ON DELETE SET NULL`,
  `ALTER TABLE expert_payables ADD COLUMN IF NOT EXISTS payment_method text`,
  `ALTER TABLE expert_payables ADD COLUMN IF NOT EXISTS payment_reference_number text`,
  `ALTER TABLE expert_payables ADD COLUMN IF NOT EXISTS payment_notes text`,
  `ALTER TABLE expert_payables ADD COLUMN IF NOT EXISTS voided_at timestamp`,
  `ALTER TABLE expert_payables ADD COLUMN IF NOT EXISTS voided_by_user_id integer REFERENCES users(id) ON DELETE SET NULL`,
  `ALTER TABLE expert_payables ADD COLUMN IF NOT EXISTS void_reason text`,
  `ALTER TABLE expert_payables ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now() NOT NULL`,
  `ALTER TABLE expert_payables ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now() NOT NULL`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_expert_payables_consultation ON expert_payables(consultation_id)`,
  `CREATE INDEX IF NOT EXISTS idx_expert_payables_status ON expert_payables(status)`,
  `CREATE INDEX IF NOT EXISTS idx_expert_payables_project ON expert_payables(project_id)`,
  `CREATE INDEX IF NOT EXISTS idx_expert_payables_expert ON expert_payables(expert_id)`,
  `CREATE TABLE IF NOT EXISTS invoices (
    id serial PRIMARY KEY,
    draft_number text NOT NULL UNIQUE,
    invoice_number text UNIQUE,
    client_organization_id integer NOT NULL REFERENCES client_organizations(id) ON DELETE RESTRICT,
    invoice_date timestamp NOT NULL,
    period_start timestamp,
    period_end timestamp,
    currency text NOT NULL DEFAULT 'USD',
    subtotal numeric(12,2) NOT NULL DEFAULT 0,
    total numeric(12,2) NOT NULL DEFAULT 0,
    status text NOT NULL DEFAULT 'draft',
    notes text,
    issued_at timestamp,
    issued_by_user_id integer REFERENCES users(id),
    sent_at timestamp,
    sent_by_user_id integer REFERENCES users(id),
    sent_method text,
    sent_recipient_email text,
    sent_notes text,
    paid_at timestamp,
    paid_by_user_id integer REFERENCES users(id),
    payment_method text,
    payment_reference_number text,
    payment_notes text,
    created_at timestamp DEFAULT now() NOT NULL,
    updated_at timestamp DEFAULT now() NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS invoice_line_items (
    id serial PRIMARY KEY,
    invoice_id integer NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
    billable_usage_id integer NOT NULL REFERENCES billable_usage(id) ON DELETE RESTRICT,
    description text NOT NULL,
    service_date timestamp NOT NULL,
    project_id integer NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
    expert_id integer NOT NULL REFERENCES experts(id) ON DELETE RESTRICT,
    cu_used numeric(10,2) NOT NULL,
    cu_rate numeric(10,2) NOT NULL,
    amount numeric(12,2) NOT NULL,
    created_at timestamp DEFAULT now() NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS expenses (
    id serial PRIMARY KEY,
    expense_id text NOT NULL UNIQUE,
    vendor text NOT NULL,
    category text NOT NULL,
    description text,
    amount numeric(12,2) NOT NULL DEFAULT 0,
    currency text NOT NULL DEFAULT 'USD',
    billing_type text NOT NULL,
    expense_date timestamp NOT NULL,
    renewal_date timestamp,
    payment_method text,
    status text NOT NULL DEFAULT 'Active',
    owner_id integer REFERENCES users(id),
    approved_by integer REFERENCES users(id),
    approved_at timestamp,
    accounting_status text NOT NULL DEFAULT 'Pending',
    notes text,
    receipt_file_name text,
    receipt_mime_type text,
    receipt_file_size integer,
    receipt_uploaded_by integer REFERENCES users(id),
    receipt_uploaded_at timestamp,
    receipt_data text,
    created_at timestamp DEFAULT now() NOT NULL,
    updated_at timestamp DEFAULT now() NOT NULL
  )`,
  `ALTER TABLE expenses ADD COLUMN IF NOT EXISTS expense_id text`,
  `ALTER TABLE expenses ADD COLUMN IF NOT EXISTS vendor text`,
  `ALTER TABLE expenses ADD COLUMN IF NOT EXISTS category text`,
  `ALTER TABLE expenses ADD COLUMN IF NOT EXISTS description text`,
  `ALTER TABLE expenses ADD COLUMN IF NOT EXISTS amount numeric(12,2) DEFAULT 0`,
  `ALTER TABLE expenses ADD COLUMN IF NOT EXISTS currency text DEFAULT 'USD'`,
  `ALTER TABLE expenses ADD COLUMN IF NOT EXISTS billing_type text`,
  `ALTER TABLE expenses ADD COLUMN IF NOT EXISTS expense_date timestamp`,
  `ALTER TABLE expenses ADD COLUMN IF NOT EXISTS renewal_date timestamp`,
  `ALTER TABLE expenses ADD COLUMN IF NOT EXISTS payment_method text`,
  `ALTER TABLE expenses ADD COLUMN IF NOT EXISTS status text DEFAULT 'Active'`,
  `ALTER TABLE expenses ADD COLUMN IF NOT EXISTS owner_id integer REFERENCES users(id)`,
  `ALTER TABLE expenses ADD COLUMN IF NOT EXISTS approved_by integer REFERENCES users(id)`,
  `ALTER TABLE expenses ADD COLUMN IF NOT EXISTS approved_at timestamp`,
  `ALTER TABLE expenses ADD COLUMN IF NOT EXISTS accounting_status text DEFAULT 'Pending'`,
  `ALTER TABLE expenses ADD COLUMN IF NOT EXISTS notes text`,
  `ALTER TABLE expenses ADD COLUMN IF NOT EXISTS receipt_file_name text`,
  `ALTER TABLE expenses ADD COLUMN IF NOT EXISTS receipt_mime_type text`,
  `ALTER TABLE expenses ADD COLUMN IF NOT EXISTS receipt_file_size integer`,
  `ALTER TABLE expenses ADD COLUMN IF NOT EXISTS receipt_uploaded_by integer REFERENCES users(id)`,
  `ALTER TABLE expenses ADD COLUMN IF NOT EXISTS receipt_uploaded_at timestamp`,
  `ALTER TABLE expenses ADD COLUMN IF NOT EXISTS receipt_data text`,
  `ALTER TABLE expenses ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now() NOT NULL`,
  `ALTER TABLE expenses ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now() NOT NULL`,
  `CREATE UNIQUE INDEX IF NOT EXISTS expenses_expense_id_unique ON expenses(expense_id) WHERE expense_id IS NOT NULL`,
  `ALTER TABLE invoice_line_items DROP CONSTRAINT IF EXISTS invoice_line_items_billable_usage_id_key`,
  `ALTER TABLE invoice_line_items DROP CONSTRAINT IF EXISTS invoice_line_items_billable_usage_id_unique`,
  `DROP INDEX IF EXISTS invoice_line_items_billable_usage_id_key`,
  `DROP INDEX IF EXISTS invoice_line_items_billable_usage_id_unique`,
  `ALTER TABLE invoices ADD COLUMN IF NOT EXISTS invoice_number text`,
  `ALTER TABLE invoices ADD COLUMN IF NOT EXISTS issued_at timestamp`,
  `ALTER TABLE invoices ADD COLUMN IF NOT EXISTS issued_by_user_id integer REFERENCES users(id)`,
  `ALTER TABLE invoices ADD COLUMN IF NOT EXISTS sent_at timestamp`,
  `ALTER TABLE invoices ADD COLUMN IF NOT EXISTS sent_by_user_id integer REFERENCES users(id)`,
  `ALTER TABLE invoices ADD COLUMN IF NOT EXISTS sent_method text`,
  `ALTER TABLE invoices ADD COLUMN IF NOT EXISTS sent_recipient_email text`,
  `ALTER TABLE invoices ADD COLUMN IF NOT EXISTS sent_notes text`,
  `ALTER TABLE invoices ADD COLUMN IF NOT EXISTS paid_at timestamp`,
  `ALTER TABLE invoices ADD COLUMN IF NOT EXISTS paid_by_user_id integer REFERENCES users(id)`,
  `ALTER TABLE invoices ADD COLUMN IF NOT EXISTS payment_method text`,
  `ALTER TABLE invoices ADD COLUMN IF NOT EXISTS payment_reference_number text`,
  `ALTER TABLE invoices ADD COLUMN IF NOT EXISTS payment_notes text`,
  `CREATE UNIQUE INDEX IF NOT EXISTS invoices_invoice_number_unique ON invoices(invoice_number) WHERE invoice_number IS NOT NULL`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS project_overview text`,
  `ALTER TABLE client_organizations ADD COLUMN IF NOT EXISTS client_type text`,
  `ALTER TABLE client_organizations ADD COLUMN IF NOT EXISTS legal_entity_name text`,
  `ALTER TABLE client_organizations ADD COLUMN IF NOT EXISTS contract_type text`,
  `ALTER TABLE client_organizations ADD COLUMN IF NOT EXISTS pricing_model text`,
  `ALTER TABLE client_organizations ADD COLUMN IF NOT EXISTS currency text DEFAULT 'USD'`,
  `ALTER TABLE client_organizations ADD COLUMN IF NOT EXISTS default_cu_rate numeric(10,2)`,
  `ALTER TABLE client_organizations ADD COLUMN IF NOT EXISTS purchased_cu numeric(10,2)`,
  `ALTER TABLE client_organizations ADD COLUMN IF NOT EXISTS retainer_cu_allowance numeric(10,2)`,
  `ALTER TABLE client_organizations ADD COLUMN IF NOT EXISTS retainer_period text`,
  `ALTER TABLE client_organizations ADD COLUMN IF NOT EXISTS contracted_cu numeric(10,2)`,
  `ALTER TABLE client_organizations ADD COLUMN IF NOT EXISTS payment_terms text`,
  `ALTER TABLE client_organizations ADD COLUMN IF NOT EXISTS contract_start_date timestamp`,
  `ALTER TABLE client_organizations ADD COLUMN IF NOT EXISTS contract_end_date timestamp`,
  `ALTER TABLE client_organizations ADD COLUMN IF NOT EXISTS credit_balance numeric(10,2)`,
  `ALTER TABLE client_organizations ADD COLUMN IF NOT EXISTS retainer_balance numeric(10,2)`,
  `ALTER TABLE client_organizations ADD COLUMN IF NOT EXISTS commercial_notes text`,
  `ALTER TABLE companies ADD COLUMN IF NOT EXISTS name text`,
  `ALTER TABLE companies ADD COLUMN IF NOT EXISTS normalized_name text`,
  `ALTER TABLE companies ADD COLUMN IF NOT EXISTS legal_name text`,
  `ALTER TABLE companies ADD COLUMN IF NOT EXISTS official_website text`,
  `ALTER TABLE companies ADD COLUMN IF NOT EXISTS linkedin_url text`,
  `ALTER TABLE companies ADD COLUMN IF NOT EXISTS country text`,
  `ALTER TABLE companies ADD COLUMN IF NOT EXISTS company_type text`,
  `ALTER TABLE companies ADD COLUMN IF NOT EXISTS industry text`,
  `ALTER TABLE companies ADD COLUMN IF NOT EXISTS city text`,
  `ALTER TABLE companies ADD COLUMN IF NOT EXISTS description text`,
  `ALTER TABLE companies ADD COLUMN IF NOT EXISTS ownership_notes text`,
  `ALTER TABLE companies ADD COLUMN IF NOT EXISTS notes text`,
  `ALTER TABLE companies ADD COLUMN IF NOT EXISTS status text DEFAULT 'active'`,
  `ALTER TABLE companies ADD COLUMN IF NOT EXISTS dnc_status text DEFAULT 'none'`,
  `ALTER TABLE companies ADD COLUMN IF NOT EXISTS verification_status text DEFAULT 'unverified'`,
  `ALTER TABLE companies ALTER COLUMN status SET DEFAULT 'active'`,
  `UPDATE companies SET status = 'active' WHERE status = 'unverified'`,
  `ALTER TABLE companies ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now()`,
  `ALTER TABLE companies ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now()`,
  `ALTER TABLE company_aliases ADD COLUMN IF NOT EXISTS company_id integer REFERENCES companies(id) ON DELETE CASCADE`,
  `ALTER TABLE company_aliases ADD COLUMN IF NOT EXISTS alias text`,
  `ALTER TABLE company_aliases ADD COLUMN IF NOT EXISTS normalized_alias text`,
  `ALTER TABLE company_aliases ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now()`,
  `CREATE INDEX IF NOT EXISTS companies_normalized_name_idx ON companies(normalized_name)`,
  `CREATE INDEX IF NOT EXISTS company_aliases_normalized_alias_idx ON company_aliases(normalized_alias)`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS client_organization_id integer REFERENCES client_organizations(id)`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS client_company text`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS client_poc_name text`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS client_poc_email text`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS client_request_notes text`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS external_advisor_brief text`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS region text`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS budget numeric(10,2)`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS start_date timestamp`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS end_date timestamp`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS due_date timestamp`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS created_by_pm_id integer REFERENCES users(id)`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS assigned_ra_id integer REFERENCES users(id)`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS assigned_ra_ids integer[]`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS total_cu_used numeric(10,2) DEFAULT 0`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS cu_rate_per_cu numeric(10,2) DEFAULT 1150`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now()`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS password_hash text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS phone text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS linkedin_url text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS country text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS city text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS timezone text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS whatsapp text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS sector_expertise text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS regional_expertise text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS areas_of_expertise text[]`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS company text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS past_employers text[]`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS job_title text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS bio text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS work_history jsonb`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS biography text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS status text DEFAULT 'available'`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS available_now boolean DEFAULT true`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS next_available_date timestamp`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS total_hours_worked numeric(10,2) DEFAULT 0`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS recruited_by text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS sourced_by_ra_id integer REFERENCES users(id)`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS sourced_at timestamp`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS terms_accepted boolean DEFAULT false`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS lgpd_accepted boolean DEFAULT false`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS billing_info text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS languages text[]`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now()`,
  `ALTER TABLE project_angles ADD COLUMN IF NOT EXISTS project_id integer REFERENCES projects(id) ON DELETE CASCADE`,
  `ALTER TABLE project_angles ADD COLUMN IF NOT EXISTS title text`,
  `ALTER TABLE project_angles ADD COLUMN IF NOT EXISTS description text`,
  `ALTER TABLE project_angles ADD COLUMN IF NOT EXISTS order_index integer DEFAULT 0`,
  `ALTER TABLE project_angles ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now()`,
  `ALTER TABLE project_angles ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now()`,
  `ALTER TABLE vetting_questions ADD COLUMN IF NOT EXISTS project_id integer REFERENCES projects(id) ON DELETE CASCADE`,
  `ALTER TABLE vetting_questions ADD COLUMN IF NOT EXISTS angle_id integer REFERENCES project_angles(id) ON DELETE CASCADE`,
  `ALTER TABLE vetting_questions ADD COLUMN IF NOT EXISTS question text`,
  `ALTER TABLE vetting_questions ADD COLUMN IF NOT EXISTS question_type text DEFAULT 'text'`,
  `ALTER TABLE vetting_questions ADD COLUMN IF NOT EXISTS order_index integer DEFAULT 0`,
  `ALTER TABLE vetting_questions ADD COLUMN IF NOT EXISTS is_required boolean DEFAULT true`,
  `ALTER TABLE vetting_questions ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now()`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS project_id integer REFERENCES projects(id) ON DELETE CASCADE`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS expert_id integer REFERENCES experts(id) ON DELETE CASCADE`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS angle_ids integer[]`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS status text DEFAULT 'assigned'`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS invitation_status text DEFAULT 'not_invited'`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS pipeline_status text DEFAULT 'interested'`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS source_type text DEFAULT 'internal_db'`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS sourced_by_ra_id integer REFERENCES users(id)`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS assigned_at timestamp DEFAULT now()`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS invited_at timestamp`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS opened_at timestamp`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS responded_at timestamp`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS invitation_token text UNIQUE`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS vq_answers jsonb`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS availability_note text`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS availability_slots jsonb`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS expected_hourly_rate_usd numeric(10,2)`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS terms_accepted boolean DEFAULT false`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS lgpd_accepted boolean DEFAULT false`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS accepted_at timestamp`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS ip_address text`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS user_agent text`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS consent_language text`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS terms_version text`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS privacy_policy_version text`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS conflict_check text`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS application_status text DEFAULT 'pending_review'`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS notes text`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS last_activity_at timestamp`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS project_id integer REFERENCES projects(id) ON DELETE CASCADE`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS expert_id integer REFERENCES experts(id) ON DELETE CASCADE`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS project_expert_id integer REFERENCES project_experts(id)`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS pm_id integer REFERENCES users(id)`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS ra_id integer REFERENCES users(id)`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS call_date timestamp`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS scheduled_start_time timestamp`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS scheduled_end_time timestamp`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS timezone text`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS actual_duration_minutes integer`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS duration_minutes integer`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS cu_used numeric(10,2) DEFAULT 0`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending'`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS completed_at timestamp`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS zoom_link text`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS recording_url text`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS notes text`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now()`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS consultation_id text`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS project_id integer REFERENCES projects(id) ON DELETE SET NULL`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS call_record_id integer REFERENCES call_records(id) ON DELETE SET NULL`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS month text`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS call_date timestamp`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS client_type text`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS industry text`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS market text`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS geography text`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS client_question text`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS observed_trend text`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS key_tags text[]`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS signal_strength text`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS company_mentioned text`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS expert_seniority text`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS call_duration_min integer`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS recording_link text`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS transcript_link text`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS pm_notes text`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS insight_title text`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS core_observation text`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS evidence_summary text`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS business_implication text`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS signal_type text`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS confidence_level text`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS confidence_reason text`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS recommended_follow_up_questions text[]`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS report_visibility text DEFAULT 'internal'`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS review_status text DEFAULT 'pm_reviewed'`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS reviewed_by integer REFERENCES users(id)`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS reviewed_at timestamp`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS approved_by integer REFERENCES users(id)`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS approved_at timestamp`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS source_type text DEFAULT 'manual'`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS generated_at timestamp`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS internal_notes text`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now()`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now()`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS project_id integer REFERENCES projects(id) ON DELETE CASCADE`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS token text`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS ra_id integer REFERENCES users(id)`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS expert_id integer REFERENCES experts(id)`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS angle_ids integer[]`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS invite_type text DEFAULT 'general'`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS candidate_name text`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS candidate_email text`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending'`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS recruited_by text DEFAULT 'system'`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS expires_at timestamp`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS used_at timestamp`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now()`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now()`,
  `CREATE TABLE IF NOT EXISTS advisor_project_invitations (
    id serial PRIMARY KEY,
    project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    expert_id integer NOT NULL REFERENCES experts(id) ON DELETE CASCADE,
    email text NOT NULL,
    token text,
    status text NOT NULL DEFAULT 'not_sent',
    sent_at timestamp,
    submitted_at timestamp,
    expires_at timestamp,
    created_by integer REFERENCES users(id),
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now()
  )`,
  `ALTER TABLE advisor_project_invitations ADD COLUMN IF NOT EXISTS project_id integer REFERENCES projects(id) ON DELETE CASCADE`,
  `ALTER TABLE advisor_project_invitations ADD COLUMN IF NOT EXISTS expert_id integer REFERENCES experts(id) ON DELETE CASCADE`,
  `ALTER TABLE advisor_project_invitations ADD COLUMN IF NOT EXISTS email text`,
  `ALTER TABLE advisor_project_invitations ADD COLUMN IF NOT EXISTS token text`,
  `ALTER TABLE advisor_project_invitations ADD COLUMN IF NOT EXISTS status text DEFAULT 'not_sent'`,
  `ALTER TABLE advisor_project_invitations ADD COLUMN IF NOT EXISTS sent_at timestamp`,
  `ALTER TABLE advisor_project_invitations ADD COLUMN IF NOT EXISTS submitted_at timestamp`,
  `ALTER TABLE advisor_project_invitations ADD COLUMN IF NOT EXISTS expires_at timestamp`,
  `ALTER TABLE advisor_project_invitations ADD COLUMN IF NOT EXISTS created_by integer REFERENCES users(id)`,
  `ALTER TABLE advisor_project_invitations ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now()`,
  `ALTER TABLE advisor_project_invitations ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now()`,
  `CREATE INDEX IF NOT EXISTS idx_advisor_project_invitations_project ON advisor_project_invitations(project_id)`,
  `CREATE INDEX IF NOT EXISTS idx_advisor_project_invitations_project_expert ON advisor_project_invitations(project_id, expert_id)`,
  `CREATE INDEX IF NOT EXISTS idx_advisor_project_invitations_token ON advisor_project_invitations(token)`,
  `CREATE TABLE IF NOT EXISTS advisor_project_responses (
    id serial PRIMARY KEY,
    invitation_id integer NOT NULL REFERENCES advisor_project_invitations(id) ON DELETE CASCADE,
    project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    expert_id integer NOT NULL REFERENCES experts(id) ON DELETE CASCADE,
    answers jsonb NOT NULL,
    consent_accepted boolean NOT NULL DEFAULT false,
    submitted_at timestamp NOT NULL DEFAULT now(),
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now()
  )`,
  `ALTER TABLE advisor_project_responses ADD COLUMN IF NOT EXISTS invitation_id integer REFERENCES advisor_project_invitations(id) ON DELETE CASCADE`,
  `ALTER TABLE advisor_project_responses ADD COLUMN IF NOT EXISTS project_id integer REFERENCES projects(id) ON DELETE CASCADE`,
  `ALTER TABLE advisor_project_responses ADD COLUMN IF NOT EXISTS expert_id integer REFERENCES experts(id) ON DELETE CASCADE`,
  `ALTER TABLE advisor_project_responses ADD COLUMN IF NOT EXISTS answers jsonb`,
  `ALTER TABLE advisor_project_responses ADD COLUMN IF NOT EXISTS consent_accepted boolean DEFAULT false`,
  `ALTER TABLE advisor_project_responses ADD COLUMN IF NOT EXISTS submitted_at timestamp DEFAULT now()`,
  `ALTER TABLE advisor_project_responses ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now()`,
  `ALTER TABLE advisor_project_responses ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now()`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_advisor_project_responses_invitation ON advisor_project_responses(invitation_id)`,
  `CREATE INDEX IF NOT EXISTS idx_advisor_project_responses_project ON advisor_project_responses(project_id)`,
  `CREATE INDEX IF NOT EXISTS idx_advisor_project_responses_expert ON advisor_project_responses(expert_id)`,
  `CREATE TABLE IF NOT EXISTS advisor_project_invitation_email_sends (
    id serial PRIMARY KEY,
    project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    invitation_id integer NOT NULL REFERENCES advisor_project_invitations(id) ON DELETE CASCADE,
    expert_id integer REFERENCES experts(id) ON DELETE SET NULL,
    sent_by_user_id integer REFERENCES users(id) ON DELETE SET NULL,
    from_email text NOT NULL,
    from_name text,
    to_email text NOT NULL,
    subject text NOT NULL,
    body text NOT NULL,
    email_type text NOT NULL DEFAULT 'initial_invite',
    provider text NOT NULL DEFAULT 'zoho',
    provider_message_id text,
    status text NOT NULL DEFAULT 'sent',
    sent_at timestamp DEFAULT now() NOT NULL,
    created_at timestamp DEFAULT now() NOT NULL
  )`,
  `ALTER TABLE advisor_project_invitation_email_sends ADD COLUMN IF NOT EXISTS project_id integer REFERENCES projects(id) ON DELETE CASCADE`,
  `ALTER TABLE advisor_project_invitation_email_sends ADD COLUMN IF NOT EXISTS invitation_id integer REFERENCES advisor_project_invitations(id) ON DELETE CASCADE`,
  `ALTER TABLE advisor_project_invitation_email_sends ADD COLUMN IF NOT EXISTS expert_id integer REFERENCES experts(id) ON DELETE SET NULL`,
  `ALTER TABLE advisor_project_invitation_email_sends ADD COLUMN IF NOT EXISTS sent_by_user_id integer REFERENCES users(id) ON DELETE SET NULL`,
  `ALTER TABLE advisor_project_invitation_email_sends ADD COLUMN IF NOT EXISTS from_email text`,
  `ALTER TABLE advisor_project_invitation_email_sends ADD COLUMN IF NOT EXISTS from_name text`,
  `ALTER TABLE advisor_project_invitation_email_sends ADD COLUMN IF NOT EXISTS to_email text`,
  `ALTER TABLE advisor_project_invitation_email_sends ADD COLUMN IF NOT EXISTS subject text`,
  `ALTER TABLE advisor_project_invitation_email_sends ADD COLUMN IF NOT EXISTS body text`,
  `ALTER TABLE advisor_project_invitation_email_sends ADD COLUMN IF NOT EXISTS email_type text DEFAULT 'initial_invite'`,
  `ALTER TABLE advisor_project_invitation_email_sends ADD COLUMN IF NOT EXISTS provider text DEFAULT 'zoho'`,
  `ALTER TABLE advisor_project_invitation_email_sends ADD COLUMN IF NOT EXISTS provider_message_id text`,
  `ALTER TABLE advisor_project_invitation_email_sends ADD COLUMN IF NOT EXISTS status text DEFAULT 'sent'`,
  `ALTER TABLE advisor_project_invitation_email_sends ADD COLUMN IF NOT EXISTS sent_at timestamp DEFAULT now()`,
  `ALTER TABLE advisor_project_invitation_email_sends ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now()`,
  `CREATE INDEX IF NOT EXISTS idx_advisor_project_invitation_email_sends_project_invitation ON advisor_project_invitation_email_sends(project_id, invitation_id)`,
  `CREATE INDEX IF NOT EXISTS idx_advisor_project_invitation_email_sends_sent_by_user ON advisor_project_invitation_email_sends(sent_by_user_id)`,
  `ALTER TABLE project_activities ADD COLUMN IF NOT EXISTS user_id integer REFERENCES users(id)`,
  `ALTER TABLE project_activities ADD COLUMN IF NOT EXISTS project_id integer REFERENCES projects(id) ON DELETE CASCADE`,
  `ALTER TABLE project_activities ADD COLUMN IF NOT EXISTS expert_id integer REFERENCES experts(id)`,
  `ALTER TABLE project_activities ADD COLUMN IF NOT EXISTS activity_type text`,
  `ALTER TABLE project_activities ADD COLUMN IF NOT EXISTS description text`,
  `ALTER TABLE project_activities ADD COLUMN IF NOT EXISTS metadata jsonb`,
  `ALTER TABLE project_activities ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now()`
];

export async function ensureDatabaseCompatibility() {
  for (const statement of compatibilityStatements) {
    try {
      await pool.query(statement);
    } catch (error) {
      console.error("Database compatibility check failed:", statement, error);
      throw error;
    }
  }
}
