import { Pool, neonConfig } from '@neondatabase/serverless';
import { drizzle } from 'drizzle-orm/neon-serverless';
import ws from "ws";
import * as schema from "@shared/schema";

neonConfig.webSocketConstructor = ws;

if (!process.env.DATABASE_URL) {
  throw new Error(
    "DATABASE_URL must be set. Did you forget to provision a database?",
  );
}

export const pool = new Pool({ connectionString: process.env.DATABASE_URL });
export const db = drizzle({ client: pool, schema });

const compatibilityStatements = [
  `CREATE TABLE IF NOT EXISTS client_organizations (
    id serial PRIMARY KEY,
    name text NOT NULL,
    industry text NOT NULL,
    billing_address text,
    main_pm_id integer REFERENCES users(id),
    total_cu_used numeric(10,2) DEFAULT 0,
    created_at timestamp DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS client_pocs (
    id serial PRIMARY KEY,
    organization_id integer NOT NULL REFERENCES client_organizations(id) ON DELETE CASCADE,
    name text NOT NULL,
    email text NOT NULL,
    phone text,
    job_title text,
    created_at timestamp DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS project_angles (
    id serial PRIMARY KEY,
    project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    title text NOT NULL,
    description text,
    order_index integer DEFAULT 0,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS vetting_questions (
    id serial PRIMARY KEY,
    project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    angle_id integer REFERENCES project_angles(id) ON DELETE CASCADE,
    question text NOT NULL,
    question_type text DEFAULT 'text',
    order_index integer DEFAULT 0,
    is_required boolean DEFAULT true,
    created_at timestamp DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS project_experts (
    id serial PRIMARY KEY,
    project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    expert_id integer NOT NULL REFERENCES experts(id) ON DELETE CASCADE,
    status text DEFAULT 'assigned',
    invitation_status text DEFAULT 'not_invited',
    pipeline_status text DEFAULT 'interested',
    source_type text DEFAULT 'internal_db',
    assigned_at timestamp DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS call_records (
    id serial PRIMARY KEY,
    project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    expert_id integer NOT NULL REFERENCES experts(id) ON DELETE CASCADE,
    call_date timestamp NOT NULL,
    duration_minutes integer NOT NULL,
    cu_used numeric(10,2) NOT NULL,
    status text DEFAULT 'pending',
    created_at timestamp DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS expert_invitation_links (
    id serial PRIMARY KEY,
    token text NOT NULL UNIQUE,
    project_id integer REFERENCES projects(id) ON DELETE CASCADE,
    ra_id integer REFERENCES users(id),
    expert_id integer REFERENCES experts(id),
    invite_type text DEFAULT 'general',
    status text DEFAULT 'pending',
    recruited_by text DEFAULT 'system',
    is_active boolean DEFAULT true,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS project_activities (
    id serial PRIMARY KEY,
    project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    user_id integer REFERENCES users(id),
    expert_id integer REFERENCES experts(id),
    activity_type text NOT NULL,
    description text NOT NULL,
    metadata jsonb,
    created_at timestamp DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS usage_records (
    id serial PRIMARY KEY,
    project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    expert_id integer NOT NULL REFERENCES experts(id) ON DELETE CASCADE,
    call_date timestamp NOT NULL,
    duration_minutes integer NOT NULL,
    credits_used numeric(10,2) NOT NULL,
    notes text,
    created_at timestamp DEFAULT now()
  )`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS project_overview text`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS client_organization_id integer REFERENCES client_organizations(id)`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS client_company text`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS client_poc_name text`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS client_poc_email text`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS client_request_notes text`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS region text`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS budget numeric(10,2)`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS start_date timestamp`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS end_date timestamp`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS due_date timestamp`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS created_by_pm_id integer REFERENCES users(id)`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS assigned_ra_id integer REFERENCES users(id)`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS assigned_ra_ids integer[]`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS total_cu_used numeric(10,2) DEFAULT 0`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS cu_rate_per_cu numeric(10,2) DEFAULT 1150`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now()`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS password_hash text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS phone text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS linkedin_url text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS country text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS city text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS timezone text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS whatsapp text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS sector_expertise text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS regional_expertise text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS areas_of_expertise text[]`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS company text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS past_employers text[]`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS job_title text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS bio text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS work_history jsonb`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS biography text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS status text DEFAULT 'available'`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS available_now boolean DEFAULT true`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS next_available_date timestamp`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS total_hours_worked numeric(10,2) DEFAULT 0`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS recruited_by text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS sourced_by_ra_id integer REFERENCES users(id)`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS sourced_at timestamp`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS terms_accepted boolean DEFAULT false`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS lgpd_accepted boolean DEFAULT false`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS billing_info text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS languages text[]`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now()`,
  `ALTER TABLE project_angles ADD COLUMN IF NOT EXISTS project_id integer REFERENCES projects(id) ON DELETE CASCADE`,
  `ALTER TABLE project_angles ADD COLUMN IF NOT EXISTS title text`,
  `ALTER TABLE project_angles ADD COLUMN IF NOT EXISTS description text`,
  `ALTER TABLE project_angles ADD COLUMN IF NOT EXISTS order_index integer DEFAULT 0`,
  `ALTER TABLE project_angles ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now()`,
  `ALTER TABLE project_angles ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now()`,
  `ALTER TABLE vetting_questions ADD COLUMN IF NOT EXISTS project_id integer REFERENCES projects(id) ON DELETE CASCADE`,
  `ALTER TABLE vetting_questions ADD COLUMN IF NOT EXISTS angle_id integer REFERENCES project_angles(id) ON DELETE CASCADE`,
  `ALTER TABLE vetting_questions ADD COLUMN IF NOT EXISTS question text`,
  `ALTER TABLE vetting_questions ADD COLUMN IF NOT EXISTS question_type text DEFAULT 'text'`,
  `ALTER TABLE vetting_questions ADD COLUMN IF NOT EXISTS order_index integer DEFAULT 0`,
  `ALTER TABLE vetting_questions ADD COLUMN IF NOT EXISTS is_required boolean DEFAULT true`,
  `ALTER TABLE vetting_questions ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now()`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS project_id integer REFERENCES projects(id) ON DELETE CASCADE`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS expert_id integer REFERENCES experts(id) ON DELETE CASCADE`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS angle_ids integer[]`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS status text DEFAULT 'assigned'`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS invitation_status text DEFAULT 'not_invited'`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS pipeline_status text DEFAULT 'interested'`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS source_type text DEFAULT 'internal_db'`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS sourced_by_ra_id integer REFERENCES users(id)`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS assigned_at timestamp DEFAULT now()`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS invited_at timestamp`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS opened_at timestamp`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS responded_at timestamp`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS invitation_token text UNIQUE`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS vq_answers jsonb`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS availability_note text`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS availability_slots jsonb`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS expected_hourly_rate_usd numeric(10,2)`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS terms_accepted boolean DEFAULT false`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS lgpd_accepted boolean DEFAULT false`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS accepted_at timestamp`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS ip_address text`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS user_agent text`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS conflict_check text`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS application_status text DEFAULT 'pending_review'`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS notes text`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS last_activity_at timestamp`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS project_id integer REFERENCES projects(id) ON DELETE CASCADE`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS expert_id integer REFERENCES experts(id) ON DELETE CASCADE`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS project_expert_id integer REFERENCES project_experts(id)`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS pm_id integer REFERENCES users(id)`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS ra_id integer REFERENCES users(id)`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS call_date timestamp`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS scheduled_start_time timestamp`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS scheduled_end_time timestamp`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS actual_duration_minutes integer`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS duration_minutes integer`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS cu_used numeric(10,2) DEFAULT 0`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending'`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS completed_at timestamp`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS zoom_link text`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS recording_url text`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS notes text`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now()`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS project_id integer REFERENCES projects(id) ON DELETE CASCADE`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS token text`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS ra_id integer REFERENCES users(id)`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS expert_id integer REFERENCES experts(id)`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS angle_ids integer[]`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS invite_type text DEFAULT 'general'`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS candidate_name text`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS candidate_email text`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending'`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS recruited_by text DEFAULT 'system'`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS expires_at timestamp`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS used_at timestamp`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now()`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now()`,
  `ALTER TABLE project_activities ADD COLUMN IF NOT EXISTS user_id integer REFERENCES users(id)`,
  `ALTER TABLE project_activities ADD COLUMN IF NOT EXISTS project_id integer REFERENCES projects(id) ON DELETE CASCADE`,
  `ALTER TABLE project_activities ADD COLUMN IF NOT EXISTS expert_id integer REFERENCES experts(id)`,
  `ALTER TABLE project_activities ADD COLUMN IF NOT EXISTS activity_type text`,
  `ALTER TABLE project_activities ADD COLUMN IF NOT EXISTS description text`,
  `ALTER TABLE project_activities ADD COLUMN IF NOT EXISTS metadata jsonb`,
  `ALTER TABLE project_activities ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now()`
];

export async function ensureDatabaseCompatibility() {
  for (const statement of compatibilityStatements) {
    try {
      await pool.query(statement);
    } catch (error) {
      console.error("Database compatibility check failed:", statement, error);
      throw error;
    }
  }
}
