import { Pool, neonConfig } from '@neondatabase/serverless';
import { drizzle } from 'drizzle-orm/neon-serverless';
import ws from "ws";
import * as schema from "@shared/schema";

neonConfig.webSocketConstructor = ws;

if (!process.env.DATABASE_URL) {
  throw new Error(
    "DATABASE_URL must be set. Did you forget to provision a database?",
  );
}

export const pool = new Pool({ connectionString: process.env.DATABASE_URL });
export const db = drizzle({ client: pool, schema });

const compatibilityStatements = [
  `CREATE TABLE IF NOT EXISTS users (
    id serial PRIMARY KEY,
    full_name text NOT NULL,
    email text NOT NULL UNIQUE,
    password_hash text,
    role text NOT NULL DEFAULT 'pm',
    is_active boolean NOT NULL DEFAULT true,
    must_change_password boolean NOT NULL DEFAULT false,
    created_at timestamp DEFAULT now() NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS clients (
    id serial PRIMARY KEY,
    client_name text NOT NULL,
    country text,
    region text,
    industry text,
    main_contact_name text,
    main_contact_email text,
    main_contact_phone text,
    notes text,
    status text NOT NULL DEFAULT 'prospect',
    created_at timestamp DEFAULT now() NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS client_organizations (
    id serial PRIMARY KEY,
    name text NOT NULL,
    industry text NOT NULL,
    client_type text,
    legal_entity_name text,
    contract_type text,
    pricing_model text,
    currency text DEFAULT 'USD',
    default_cu_rate numeric(10,2),
    purchased_cu numeric(10,2),
    retainer_cu_allowance numeric(10,2),
    retainer_period text,
    contracted_cu numeric(10,2),
    payment_terms text,
    contract_start_date timestamp,
    contract_end_date timestamp,
    credit_balance numeric(10,2),
    retainer_balance numeric(10,2),
    commercial_notes text,
    billing_address text,
    main_pm_id integer REFERENCES users(id),
    total_cu_used numeric(10,2) DEFAULT 0,
    created_at timestamp DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS client_pocs (
    id serial PRIMARY KEY,
    organization_id integer NOT NULL REFERENCES client_organizations(id) ON DELETE CASCADE,
    name text NOT NULL,
    email text NOT NULL,
    phone text,
    job_title text,
    created_at timestamp DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS projects (
    id serial PRIMARY KEY,
    name text NOT NULL,
    project_overview text,
    client_organization_id integer REFERENCES client_organizations(id),
    client_name text NOT NULL,
    client_company text,
    client_poc_name text,
    client_poc_email text,
    client_request_notes text,
    description text,
    industry text NOT NULL,
    region text,
    status text NOT NULL DEFAULT 'new',
    budget numeric(10,2),
    start_date timestamp,
    end_date timestamp,
    due_date timestamp,
    created_by_pm_id integer REFERENCES users(id),
    assigned_ra_id integer REFERENCES users(id),
    assigned_ra_ids integer[],
    total_cu_used numeric(10,2) DEFAULT 0,
    cu_rate_per_cu numeric(10,2) DEFAULT 1150,
    created_at timestamp DEFAULT now() NOT NULL,
    updated_at timestamp DEFAULT now() NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS experts (
    id serial PRIMARY KEY,
    name text NOT NULL,
    email text NOT NULL UNIQUE,
    password_hash text,
    phone text,
    linkedin_url text,
    country text,
    city text,
    timezone text,
    whatsapp text,
    expertise text NOT NULL,
    sector_expertise text,
    regional_expertise text,
    areas_of_expertise text[],
    industry text NOT NULL,
    company text,
    past_employers text[],
    job_title text,
    years_of_experience integer NOT NULL,
    hourly_rate numeric(10,2) NOT NULL,
    bio text,
    work_history jsonb,
    biography text,
    status text NOT NULL DEFAULT 'available',
    available_now boolean DEFAULT true,
    next_available_date timestamp,
    total_hours_worked numeric(10,2) DEFAULT 0,
    recruited_by text,
    sourced_by_ra_id integer REFERENCES users(id),
    sourced_at timestamp,
    terms_accepted boolean DEFAULT false,
    lgpd_accepted boolean DEFAULT false,
    billing_info text,
    languages text[],
    created_at timestamp DEFAULT now() NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS project_angles (
    id serial PRIMARY KEY,
    project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    title text NOT NULL,
    description text,
    order_index integer DEFAULT 0,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS vetting_questions (
    id serial PRIMARY KEY,
    project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    angle_id integer REFERENCES project_angles(id) ON DELETE CASCADE,
    question text NOT NULL,
    question_type text DEFAULT 'text',
    order_index integer DEFAULT 0,
    is_required boolean DEFAULT true,
    created_at timestamp DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS project_experts (
    id serial PRIMARY KEY,
    project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    expert_id integer NOT NULL REFERENCES experts(id) ON DELETE CASCADE,
    status text DEFAULT 'assigned',
    invitation_status text DEFAULT 'not_invited',
    pipeline_status text DEFAULT 'interested',
    source_type text DEFAULT 'internal_db',
    consent_language text,
    terms_version text,
    privacy_policy_version text,
    assigned_at timestamp DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS call_records (
    id serial PRIMARY KEY,
    project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    expert_id integer NOT NULL REFERENCES experts(id) ON DELETE CASCADE,
    call_date timestamp NOT NULL,
    timezone text,
    duration_minutes integer NOT NULL,
    cu_used numeric(10,2) NOT NULL,
    status text DEFAULT 'pending',
    created_at timestamp DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS insights (
    id serial PRIMARY KEY,
    consultation_id text NOT NULL,
    call_record_id integer REFERENCES call_records(id) ON DELETE SET NULL,
    month text NOT NULL,
    call_date timestamp NOT NULL,
    client_type text NOT NULL,
    industry text NOT NULL,
    market text NOT NULL,
    geography text NOT NULL,
    client_question text NOT NULL,
    observed_trend text NOT NULL,
    key_tags text[],
    signal_strength text NOT NULL,
    company_mentioned text,
    expert_seniority text,
    call_duration_min integer,
    recording_link text,
    transcript_link text,
    internal_notes text,
    created_at timestamp DEFAULT now() NOT NULL,
    updated_at timestamp DEFAULT now() NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS expert_invitation_links (
    id serial PRIMARY KEY,
    token text NOT NULL UNIQUE,
    project_id integer REFERENCES projects(id) ON DELETE CASCADE,
    ra_id integer REFERENCES users(id),
    expert_id integer REFERENCES experts(id),
    invite_type text DEFAULT 'general',
    status text DEFAULT 'pending',
    recruited_by text DEFAULT 'system',
    is_active boolean DEFAULT true,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS project_activities (
    id serial PRIMARY KEY,
    project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    user_id integer REFERENCES users(id),
    expert_id integer REFERENCES experts(id),
    activity_type text NOT NULL,
    description text NOT NULL,
    metadata jsonb,
    created_at timestamp DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS usage_records (
    id serial PRIMARY KEY,
    project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    expert_id integer NOT NULL REFERENCES experts(id) ON DELETE CASCADE,
    call_date timestamp NOT NULL,
    duration_minutes integer NOT NULL,
    credits_used numeric(10,2) NOT NULL,
    notes text,
    created_at timestamp DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS billable_usage (
    id serial PRIMARY KEY,
    call_record_id integer NOT NULL UNIQUE REFERENCES call_records(id) ON DELETE RESTRICT,
    client_organization_id integer REFERENCES client_organizations(id),
    project_id integer NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
    expert_id integer NOT NULL REFERENCES experts(id) ON DELETE RESTRICT,
    call_date timestamp NOT NULL,
    cu_used numeric(10,2) NOT NULL,
    currency text NOT NULL DEFAULT 'USD',
    cu_rate numeric(10,2),
    amount numeric(10,2),
    status text NOT NULL DEFAULT 'unbilled',
    source text NOT NULL DEFAULT 'completed_call_record',
    adjustment_reason text,
    created_at timestamp DEFAULT now() NOT NULL,
    updated_at timestamp DEFAULT now() NOT NULL
  )`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS project_overview text`,
  `ALTER TABLE client_organizations ADD COLUMN IF NOT EXISTS client_type text`,
  `ALTER TABLE client_organizations ADD COLUMN IF NOT EXISTS legal_entity_name text`,
  `ALTER TABLE client_organizations ADD COLUMN IF NOT EXISTS contract_type text`,
  `ALTER TABLE client_organizations ADD COLUMN IF NOT EXISTS pricing_model text`,
  `ALTER TABLE client_organizations ADD COLUMN IF NOT EXISTS currency text DEFAULT 'USD'`,
  `ALTER TABLE client_organizations ADD COLUMN IF NOT EXISTS default_cu_rate numeric(10,2)`,
  `ALTER TABLE client_organizations ADD COLUMN IF NOT EXISTS purchased_cu numeric(10,2)`,
  `ALTER TABLE client_organizations ADD COLUMN IF NOT EXISTS retainer_cu_allowance numeric(10,2)`,
  `ALTER TABLE client_organizations ADD COLUMN IF NOT EXISTS retainer_period text`,
  `ALTER TABLE client_organizations ADD COLUMN IF NOT EXISTS contracted_cu numeric(10,2)`,
  `ALTER TABLE client_organizations ADD COLUMN IF NOT EXISTS payment_terms text`,
  `ALTER TABLE client_organizations ADD COLUMN IF NOT EXISTS contract_start_date timestamp`,
  `ALTER TABLE client_organizations ADD COLUMN IF NOT EXISTS contract_end_date timestamp`,
  `ALTER TABLE client_organizations ADD COLUMN IF NOT EXISTS credit_balance numeric(10,2)`,
  `ALTER TABLE client_organizations ADD COLUMN IF NOT EXISTS retainer_balance numeric(10,2)`,
  `ALTER TABLE client_organizations ADD COLUMN IF NOT EXISTS commercial_notes text`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS client_organization_id integer REFERENCES client_organizations(id)`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS client_company text`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS client_poc_name text`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS client_poc_email text`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS client_request_notes text`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS region text`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS budget numeric(10,2)`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS start_date timestamp`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS end_date timestamp`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS due_date timestamp`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS created_by_pm_id integer REFERENCES users(id)`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS assigned_ra_id integer REFERENCES users(id)`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS assigned_ra_ids integer[]`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS total_cu_used numeric(10,2) DEFAULT 0`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS cu_rate_per_cu numeric(10,2) DEFAULT 1150`,
  `ALTER TABLE projects ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now()`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS password_hash text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS phone text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS linkedin_url text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS country text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS city text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS timezone text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS whatsapp text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS sector_expertise text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS regional_expertise text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS areas_of_expertise text[]`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS company text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS past_employers text[]`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS job_title text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS bio text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS work_history jsonb`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS biography text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS status text DEFAULT 'available'`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS available_now boolean DEFAULT true`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS next_available_date timestamp`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS total_hours_worked numeric(10,2) DEFAULT 0`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS recruited_by text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS sourced_by_ra_id integer REFERENCES users(id)`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS sourced_at timestamp`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS terms_accepted boolean DEFAULT false`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS lgpd_accepted boolean DEFAULT false`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS billing_info text`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS languages text[]`,
  `ALTER TABLE experts ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now()`,
  `ALTER TABLE project_angles ADD COLUMN IF NOT EXISTS project_id integer REFERENCES projects(id) ON DELETE CASCADE`,
  `ALTER TABLE project_angles ADD COLUMN IF NOT EXISTS title text`,
  `ALTER TABLE project_angles ADD COLUMN IF NOT EXISTS description text`,
  `ALTER TABLE project_angles ADD COLUMN IF NOT EXISTS order_index integer DEFAULT 0`,
  `ALTER TABLE project_angles ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now()`,
  `ALTER TABLE project_angles ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now()`,
  `ALTER TABLE vetting_questions ADD COLUMN IF NOT EXISTS project_id integer REFERENCES projects(id) ON DELETE CASCADE`,
  `ALTER TABLE vetting_questions ADD COLUMN IF NOT EXISTS angle_id integer REFERENCES project_angles(id) ON DELETE CASCADE`,
  `ALTER TABLE vetting_questions ADD COLUMN IF NOT EXISTS question text`,
  `ALTER TABLE vetting_questions ADD COLUMN IF NOT EXISTS question_type text DEFAULT 'text'`,
  `ALTER TABLE vetting_questions ADD COLUMN IF NOT EXISTS order_index integer DEFAULT 0`,
  `ALTER TABLE vetting_questions ADD COLUMN IF NOT EXISTS is_required boolean DEFAULT true`,
  `ALTER TABLE vetting_questions ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now()`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS project_id integer REFERENCES projects(id) ON DELETE CASCADE`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS expert_id integer REFERENCES experts(id) ON DELETE CASCADE`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS angle_ids integer[]`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS status text DEFAULT 'assigned'`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS invitation_status text DEFAULT 'not_invited'`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS pipeline_status text DEFAULT 'interested'`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS source_type text DEFAULT 'internal_db'`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS sourced_by_ra_id integer REFERENCES users(id)`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS assigned_at timestamp DEFAULT now()`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS invited_at timestamp`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS opened_at timestamp`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS responded_at timestamp`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS invitation_token text UNIQUE`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS vq_answers jsonb`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS availability_note text`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS availability_slots jsonb`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS expected_hourly_rate_usd numeric(10,2)`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS terms_accepted boolean DEFAULT false`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS lgpd_accepted boolean DEFAULT false`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS accepted_at timestamp`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS ip_address text`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS user_agent text`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS consent_language text`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS terms_version text`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS privacy_policy_version text`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS conflict_check text`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS application_status text DEFAULT 'pending_review'`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS notes text`,
  `ALTER TABLE project_experts ADD COLUMN IF NOT EXISTS last_activity_at timestamp`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS project_id integer REFERENCES projects(id) ON DELETE CASCADE`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS expert_id integer REFERENCES experts(id) ON DELETE CASCADE`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS project_expert_id integer REFERENCES project_experts(id)`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS pm_id integer REFERENCES users(id)`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS ra_id integer REFERENCES users(id)`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS call_date timestamp`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS scheduled_start_time timestamp`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS scheduled_end_time timestamp`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS timezone text`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS actual_duration_minutes integer`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS duration_minutes integer`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS cu_used numeric(10,2) DEFAULT 0`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending'`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS completed_at timestamp`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS zoom_link text`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS recording_url text`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS notes text`,
  `ALTER TABLE call_records ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now()`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS consultation_id text`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS call_record_id integer REFERENCES call_records(id) ON DELETE SET NULL`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS month text`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS call_date timestamp`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS client_type text`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS industry text`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS market text`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS geography text`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS client_question text`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS observed_trend text`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS key_tags text[]`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS signal_strength text`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS company_mentioned text`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS expert_seniority text`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS call_duration_min integer`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS recording_link text`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS transcript_link text`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS internal_notes text`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now()`,
  `ALTER TABLE insights ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now()`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS project_id integer REFERENCES projects(id) ON DELETE CASCADE`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS token text`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS ra_id integer REFERENCES users(id)`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS expert_id integer REFERENCES experts(id)`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS angle_ids integer[]`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS invite_type text DEFAULT 'general'`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS candidate_name text`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS candidate_email text`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending'`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS recruited_by text DEFAULT 'system'`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS expires_at timestamp`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS used_at timestamp`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now()`,
  `ALTER TABLE expert_invitation_links ADD COLUMN IF NOT EXISTS updated_at timestamp DEFAULT now()`,
  `ALTER TABLE project_activities ADD COLUMN IF NOT EXISTS user_id integer REFERENCES users(id)`,
  `ALTER TABLE project_activities ADD COLUMN IF NOT EXISTS project_id integer REFERENCES projects(id) ON DELETE CASCADE`,
  `ALTER TABLE project_activities ADD COLUMN IF NOT EXISTS expert_id integer REFERENCES experts(id)`,
  `ALTER TABLE project_activities ADD COLUMN IF NOT EXISTS activity_type text`,
  `ALTER TABLE project_activities ADD COLUMN IF NOT EXISTS description text`,
  `ALTER TABLE project_activities ADD COLUMN IF NOT EXISTS metadata jsonb`,
  `ALTER TABLE project_activities ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT now()`
];

export async function ensureDatabaseCompatibility() {
  for (const statement of compatibilityStatements) {
    try {
      await pool.query(statement);
    } catch (error) {
      console.error("Database compatibility check failed:", statement, error);
      throw error;
    }
  }
}
